set autoread
set incsearch
set ignorecase
set smartcase
set noswapfile

set number
set tabstop=2 shiftwidth=2 softtabstop=0
set list
set listchars=tab:»-,trail:.,eol:¬
" set listchars=tab:»-,trail:.
" set showbreak=↪\ 
set showbreak=→\ 
set linebreak
set breakindent
set expandtab
set backspace=2
"set smartindent
set clipboard+=unnamed
set showmatch
set matchtime=2
set noshowcmd

" change indent width by filetype
autocmd BufRead,BufNewFile   *.c,*.h,*.java set sw=4 sts=4 cin
autocmd BufRead,BufNewFile   *.py set sw=4 sts=4 expandtab ts=8
autocmd BufRead,BufNewFile   *.rs set sw=4 sts=4
autocmd BufRead,BufNewFile   *.php set ts=4 sts=4 sw=4


" Esc を入力しやすく
" nnoremap <C-l> <Esc>
vnoremap <C-l> <Esc>
inoremap <C-l> <Esc>
cnoremap <C-l> <Esc>
nnoremap <C-l> :w<Enter>
nnoremap <Esc><Esc> :w<Enter>
nnoremap <C-q> :q<Enter>

" 入力モードをことえり風に
inoremap <C-a> <Home>
inoremap <C-e> <End>
inoremap <C-f> <Right>
inoremap <C-b> <Left>
inoremap <C-d> <Delete>

" command mode move
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
cnoremap <C-f> <Right>
cnoremap <C-b> <Left>
cnoremap <C-d> <Delete>
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
cnoremap <C-k> <Delete>

" Resize pane
nnoremap <C-w><C-j> :res +5<CR>
nnoremap <C-w><C-k> :res -5<CR>

" Move by displayed line
nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k

" Fix the curfor when scrolling
nnoremap <C-e> zz<C-e>j
nnoremap <C-y> zz<C-y>k

nnoremap g; g;zz
nnoremap g; g,zz

inoremap <C-k> <C-o>D
" inoremap <C-j> <DOWN>
" inoremap <C-k> <UP>

nnoremap <C-j> }
nnoremap <C-k> {
vnoremap <C-j> }
vnoremap <C-k> {

let mapleader = "\<Space>"

" 改行を追加
nnoremap <leader>o :<C-u>call append(expand('.'), '')<Cr>j
nnoremap <leader>O k:<C-u>call append(expand('.'), '')<Cr>j

" file explore
nnoremap <leader><leader> :Explore<CR>

" インデント
nnoremap > >>
nnoremap < <<

" copy & paste map
nnoremap <leader>d "*dd
vnoremap <leader>d "*dd
nnoremap <leader>y "*yy
vnoremap <leader>y "*yy
nnoremap <leader>p "*p
vnoremap <leader>p "*p

" remember last postion
if has("autocmd")
  augroup redhat
    " In text files, always limit the width of text to 78 characters
    autocmd BufRead *.txt set tw=78
    " When editing a file, always jump to the last cursor position
    autocmd BufReadPost *
    \ if line("'\"") > 0 && line ("'\"") <= line("$") |
    \   exe "normal! g'\"" |
    \ endif
  augroup END
endif

autocmd Filetype php setlocal ts=4 sts=4 sw=4

"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/root/.config/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/root/.config')
  call dein#begin('/root/.config')

    " Let dein manage dein
    " Required:
    call dein#add('/root/.config/repos/github.com/Shougo/dein.vim')

    " Add or remove your plugins here:
    call dein#add('Shougo/neosnippet.vim')
    call dein#add('Shougo/neosnippet-snippets')

    " You can specify revision/branch/tag.
    call dein#add('Shougo/vimshell', { 'rev': '3787e5' })
    call dein#add('Shougo/neosnippet.vim')

    call dein#add('rking/ag.vim')
    call dein#add('scrooloose/nerdtree')

    call dein#add('ctrlpvim/ctrlp.vim')

    call dein#add('airblade/vim-gitgutter')

    call dein#add('tpope/vim-fugitive')

    " Required:
    call dein#end()
    call dein#save_state()
    endif

    " Required:
    filetype plugin indent on
    syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------

nnoremap <leader><leader> :NERDTreeToggle<CR>

let g:ctrlp_map = '<c-c>'
nnoremap <leader>nf :<C-u>NERDTreeFind<CR>¬
nnoremap <leader>gt :GitGutterToggle<CR>
nnoremap <leader>gb :Gblame<CR>
