set number
set tabstop=2 shiftwidth=2 softtabstop=0
set list
" set listchars=tab:»-,trail:.,eol:¬
set listchars=tab:»-,trail:.
set showbreak=↪\ 
set linebreak
set breakindent
set expandtab
set backspace=2
set smartindent
set clipboard=unnamed
set showmatch
set matchtime=2

" Esc を入力しやすく
" nnoremap <C-l> <Esc>
vnoremap <C-l> <Esc>
inoremap <C-l> <Esc>
cnoremap <C-l> <Esc>
nnoremap <C-l> :w<Enter>
nnoremap <Esc><Esc> :w<Enter>
nnoremap <C-q> :q<Enter>

" 入力モードをことえり風に
inoremap <C-a> <C-o>^
inoremap <C-e> <C-o>$
inoremap <C-f> <C-o>l
inoremap <C-b> <C-o>h
inoremap <C-d> <C-o>s

" 表示行単位で上下移動するように
nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k

inoremap <C-j> <DOWN>
inoremap <C-k> <UP>

nnoremap <C-j> }
nnoremap <C-k> {
vnoremap <C-j> }
vnoremap <C-k> {

let mapleader = "\<Space>"

" 改行を追加
nnoremap <leader>o :<C-u>call append(expand('.'), '')<Cr>j
nnoremap <leader>O k:<C-u>call append(expand('.'), '')<Cr>j

" file explore
nnoremap <leader><leader> :Explore<CR>

" インデント
nnoremap > >>
nnoremap < <<

" copy & paste map
nnoremap <leader>d "*dd
vnoremap <leader>d "*dd
nnoremap <leader>y "*yy
vnoremap <leader>y "*yy
nnoremap <leader>p "*p
vnoremap <leader>p "*p

" remember last postion
if has("autocmd")
  augroup redhat
    " In text files, always limit the width of text to 78 characters
    autocmd BufRead *.txt set tw=78
    " When editing a file, always jump to the last cursor position
    autocmd BufReadPost *
    \ if line("'\"") > 0 && line ("'\"") <= line("$") |
    \   exe "normal! g'\"" |
    \ endif
  augroup END
endif
